### ISSUE TITLE
Unable to use events / listener dependency

### ISSUE THREAD

**Issue by zenturacp** [bencevans/node-sonos#244]
## Expected Behavior

I want to use the example from [/examples/events.js](https://github.com/bencevans/node-sonos/blob/master/examples/events.js) but it does not work as expected

## Current Behaviour

I get following error

module.js:538
    throw err;
    ^

Error: Cannot find module '../'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/cp/Desktop/GitController/SonosController/events.js:1:77)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

## Versions (and Environment)

**node-sonos version**: Current
**OS**: MacOS

**Comment by bencevans** [comment]
You'll need to change the '../' to 'sonos' and run `npm install sonos` to download the library.

**Comment by zenturacp** [comment]
Yes - figured out.. :-) Thanks for the swift reply - you guys saved my day now my kid can't turn up the volume any more.. :)

**Comment by svrooij** [comment]
What did you build? Volume limiter?

**Comment by zenturacp** [comment]
Yes @svrooij  on event Volume change change back to Max limit for the specific device..

**Comment by zenturacp** [comment]
But it's my first Node.JS project and really need to understand the way it behaves but went from pulling to events - now I will add more speakers and after that a web interface for real humans.. 

Seems like I will be able to do that with my limited Node experience though :-) it took like 15 minutes to do the 1. Release and my evening was saved..
