### ISSUE TITLE
Alarm with id %s not found

### ISSUE THREAD

**Issue by icallend** [bencevans/node-sonos#292]
Listing all alarms works fine. Aware that comparison is '===' so have made sure types are set appropriately. Node 10.4.1 on Raspbian.

Result is:
```
Error: Alarm with id %s not found
    at ListAlarms.then.result (/home/pi/node_modules/sonos/lib/services/AlarmClock.js:117:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

Code:
```
const Sonos = require('sonos').Sonos
const sonos = new Sonos(process.env.SONOS_HOST || '192.168.0.4');

const alarmService = sonos.alarmClockService();

var reset = new Map();
reset.set("1",1);
reset.set("2",1);
reset.set("3",0);

function deactivate(){
  reset.forEach ( (value, key) => {          
    alarmService.SetAlarm(key,false).catch(err => { console.log(err) });
  });
}

deactivate();
```

**Comment by icallend** [comment]
Issue is in AlarmClock.js

```
alarmService.ListAlarms().then(result => {
  console.log(result);
}
```
returns
```
{ CurrentAlarmListVersion: 'RINCON_949F3E65133F01400:68',
  CurrentAlarmList: [ { Alarms: [Object] } ] }
```

in AlarmClock.js (beginning 105)

```
AlarmClock.prototype.PatchAlarm = function (id, options) {
  this.debug('AlarmClock.PatchAlarm(%j %j)', id, options)
  return new Promise((resolve, reject) => {
    this.ListAlarms()
      .then(result => {
        let targetAlarm = null
        for (let alarm of result.CurrentAlarmList) {
          if (alarm.ID === id) {
```
thus, `alarm of result.CurrentAlarmList` is not an individual alarm, but the json object above in which CurrentAlarmList is nested. 
For a return of an array of json objects, each an individual alarm, this must read `alarm of alarmResult.CurrentAlarmList[0].Alarms.Alarm`
