### ISSUE TITLE
Some XML parsing error

### ISSUE THREAD

**Issue by freaktechnik** [bencevans/node-sonos#323]
## Expected Behavior
No parsing errors

## Current Behavior
```
2018-08-17 14:30:20.738 sonos: Error: Non-whitespace before first tag.
2018-08-17 14:30:20.738 sonos: Line: 0
2018-08-17 14:30:20.738 sonos: Column: 1
2018-08-17 14:30:20.738 sonos: Char: N
2018-08-17 14:30:20.738 sonos:     at error (/home/martin/dev/sonos-adapter/node_modules/sax/lib/sax.js:651:10)
2018-08-17 14:30:20.738 sonos:     at strictFail (/home/martin/dev/sonos-adapter/node_modules/sax/lib/sax.js:677:7)
2018-08-17 14:30:20.738 sonos:     at beginWhiteSpace (/home/martin/dev/sonos-adapter/node_modules/sax/lib/sax.js:951:7)
2018-08-17 14:30:20.738 sonos:     at SAXParser.write (/home/martin/dev/sonos-adapter/node_modules/sax/lib/sax.js:1006:11)
2018-08-17 14:30:20.738 sonos:     at Parser.exports.Parser.Parser.parseString (/home/martin/dev/sonos-adapter/node_modules/xml2js/lib/parser.js:322:31)
2018-08-17 14:30:20.738 sonos:     at Parser.parseString (/home/martin/dev/sonos-adapter/node_modules/xml2js/lib/parser.js:5:59)
2018-08-17 14:30:20.738 sonos:     at exports.parseString (/home/martin/dev/sonos-adapter/node_modules/xml2js/lib/parser.js:354:19)
2018-08-17 14:30:20.738 sonos:     at Object.Helpers._ParseXml (/home/martin/dev/sonos-adapter/node_modules/sonos/lib/helpers.js:182:10)
2018-08-17 14:30:20.738 sonos:     at Promise (/home/martin/dev/sonos-adapter/node_modules/sonos/lib/helpers.js:202:13)
2018-08-17 14:30:20.738 sonos:     at new Promise (<anonymous>)
```

## Sample code or executed example

This happens when the player responds with "NOT_IMPLEMENTED" for "TrackMetaData" when playing from a connect input. Here the debug logs before the error:
```
2018-08-17 14:56:05.605 sonos: 2018-08-17T12:56:05.605Z sonos:service Parsed service response as JSON
2018-08-17 14:56:05.605 sonos: {
2018-08-17 14:56:05.605 sonos:   "s:Envelope": {
2018-08-17 14:56:05.605 sonos:     "xmlns:s": "http://schemas.xmlsoap.org/soap/envelope/",
2018-08-17 14:56:05.605 sonos:     "s:encodingStyle": "http://schemas.xmlsoap.org/soap/encoding/",
2018-08-17 14:56:05.605 sonos:     "s:Body": {
2018-08-17 14:56:05.605 sonos:       "u:GetPositionInfoResponse": {
2018-08-17 14:56:05.605 sonos:         "xmlns:u": "urn:schemas-upnp-org:service:AVTransport:1",
2018-08-17 14:56:05.605 sonos:         "Track": "1",
2018-08-17 14:56:05.605 sonos:         "TrackDuration": "NOT_IMPLEMENTED",
2018-08-17 14:56:05.606 sonos:         "TrackMetaData": "NOT_IMPLEMENTED",
2018-08-17 14:56:05.606 sonos:         "TrackURI": "x-rincon-stream:RINCON_000E58AF6A3401400",
2018-08-17 14:56:05.606 sonos:         "RelTime": "NOT_IMPLEMENTED",
2018-08-17 14:56:05.606 sonos:         "AbsTime": "NOT_IMPLEMENTED",
2018-08-17 14:56:05.606 sonos:         "RelCount": "2147483647",
2018-08-17 14:56:05.606 sonos:         "AbsCount": "2147483647"
2018-08-17 14:56:05.606 sonos:       }
2018-08-17 14:56:05.606 sonos:     }
2018-08-17 14:56:05.606 sonos:   }
2018-08-17 14:56:05.606 sonos: }
2018-08-17 14:56:05.606 sonos: 2018-08-17T12:56:05.605Z sonos:helpers Helpers.ParseXml "NOT_IMPLEMENTED"
```

## Versions (and Environment)

**Node version**: 10.0.0
**node-sonos version**: 1.4.0
**OS**: elementary OS

**Comment by svrooij** [comment]
Actually this error is expected, since NOT_IMPLEMENTED isn’t a correct xml format 😃 .....
Would be nice to check if the value is xml before parsing. Any ideas?

**Comment by svrooij** [comment]
I think this [line](
https://github.com/bencevans/node-sonos/blob/f3e85296ffbebc4baeb3960b52e6ac31744e4309/lib/services/AVTransport.js#L127) could easily be adjusted to don’t parse `NOT_IMPLEMENTED`
